baseURL = "http://example.org/"
languageCode = "en-us"
title = "Programma Group"
theme = "hyperspace"
[params]
  twitter = "Programma"
  facebook = "Programma"
  github = "Programma"
  linkedin = "Programma"
  instagram = "Programma"
  phone = "555-1245"
  email = "test@programma.com"
  address = "Direccion de programma"
  contactEndpoint = "https://w3e235v6ig.execute-api.us-east-1.amazonaws.com/dev/email/send"
  getInTouchText = "We are honored that you consider us to help you growth. Please fill this form and include your data or just ping us at any of the contact points on the right. For jobs please email to jobs@programma-group.com and don't forget to mention who referred you."
