baseURL = "http://example.org/"
languageCode = "en-us"
title = "Programma Group"
theme = "hyperspace"
[params]
  twitter = "Programma"
  facebook = "Programma"
  github = "Programma"
  linkedin = "Programma"
  instagram = "Programma"
  phone = "555-1245"
  email = "test@programma.com"
  address = "Direccion de programma"
  contactEndpoint = "/contact-endpoint"
  getInTouchText = "This is gonna be the text for get in touch"
